In [2]:
import torch
 
# Create a Tensor with just ones in a column
a = torch.ones(5)
 
# Print the tensor we created
print(a)
 
# tensor([1., 1., 1., 1., 1.])
 
# Create a Tensor with just zeros in a column
b = torch.zeros(5)
print(b) 

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])


In [3]:
c = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
print(c)

tensor([1., 2., 3., 4., 5.])


In [4]:
d = torch.zeros(3,2)
print(d)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
e = torch.ones(3,2)
print(e)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [6]:
f = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(f)

tensor([[1., 2.],
        [3., 4.]])


In [7]:
g = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(g)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [8]:
print(f.shape)
print(e.shape)
print(g.shape)

torch.Size([2, 2])
torch.Size([3, 2])
torch.Size([2, 2, 2])


In [9]:
print(c[2])

tensor(3.)


In [10]:
print(f[1,0])

tensor(3.)


In [11]:
print(f[1][0])

tensor(3.)


In [12]:
print(g[1,0,0])
print(g[1][0][0])

tensor(5.)
tensor(5.)


In [13]:
# All elements
print(f[:])
 
# All elements from index 1 to 2 (inclusive)
print(c[1:3])
 
# All elements till index 4 (exclusive)
print(c[:4])
 
# First row
print(f[0,:])
 
# Second column
print(f[:,1])

tensor([[1., 2.],
        [3., 4.]])
tensor([2., 3.])
tensor([1., 2., 3., 4.])
tensor([1., 2.])
tensor([2., 4.])


In [14]:
int_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(int_tensor.dtype)
 
# torch.int64
 
# What if we changed any one element to floating point number?
int_tensor = torch.tensor([[1,2,3],[4.,5,6]])
print(int_tensor.dtype)
 
# torch.float32
 
print(int_tensor)
 
# tensor([[1., 2., 3.],
#        [4., 5., 6.]])
 
 
# This can be overridden as follows
int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype=torch.int32)
print(int_tensor.dtype)
 
# torch.int32
 
print(int_tensor)
 
# tensor([[1, 2, 3],
#        [4, 5, 6]], dtype=torch.int32)

torch.int64
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [15]:
import numpy as np
 
f_numpy = f.numpy()
print(f_numpy)
 

h = np.array([[8,7,6,5],[4,3,2,1]])
h_tensor = torch.from_numpy(h)
print(h_tensor)
 

[[1. 2.]
 [3. 4.]]
tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])


In [17]:
# Create tensor
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[-1,2,-3],[4,-5,6]])
 
# Addition
print(tensor1+tensor2)
print(torch.add(tensor1,tensor2))
 
# tensor([[ 0,  4,  0],
#        [ 8,  0, 12]])
 
# Subtraction
print(tensor1-tensor2)
print(torch.sub(tensor1,tensor2))

 
# Multiplication
# Tensor with Scalar
print(tensor1 * 2)

 
# Tensor with another tensor
# Elementwise Multiplication
print(tensor1 * tensor2)

 
# Matrix multiplication
tensor3 = torch.tensor([[1,2],[3,4],[5,6]])
print(torch.mm(tensor1,tensor3))

 
# Division
# Tensor with scalar
print(tensor1/2)

 
# Tensor with another tensor
# Elementwise division
print(tensor1/tensor2)


tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[ -1,   4,  -9],
        [ 16, -25,  36]])
tensor([[22, 28],
        [49, 64]])
tensor([[0, 1, 1],
        [2, 2, 3]])
tensor([[-1,  1, -1],
        [ 1, -1,  1]])


In [18]:
tensor_cpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cpu')